language: node_js
sudo: false
node_js:
  - '4'
  - '5'
  - '6'
  - 'node'
services:
  - mongodb

# Caches exist for 45 days from creation. :-/
# But npm installing habitrpg is so slow...
cache:
  directories:
    - node_modules

before_install:
  - 'npm install -g npm@3'
  - 'npm install -g gulp'

before_script:
  - cp config.example.js config.js
  - 'npm install -g  grunt-cli mocha grunt-karma git-changelog'
  - pushd ./node_modules/habitica
  - bower install -f
  - cp config.json.example config.json
  - "until nc -z localhost 27017; do echo Waiting for MongoDB; sleep 1; done"
  - npm start &
  - popd
  - ./seedHabitRPGMongo.sh
  - "until nc -z localhost 3000; do echo Waiting for HabitRPG; sleep 1; done"
  - ps aux | grep "node"
